version: 2

models:
  - name: dim_genre
    description: "Tables showing genre count"
    columns:
      - name: genre
        description: "genre name."
      - name: genre_count
        description: "count of genre."
      - name: model_creation_date
        description: "date of model creation"
      - name: model_updated_date
        description: "date of model update"
  - name: dim_books
    description: "dimensional table containing book data for library"
    columns:
      - name: id
        description: "id for books"
      - name: title
        description: "column containing book title"
      - name: author_name
        description: "author of book"
      - name: genre
        description: "genre of book"
      - name: release_year
        description: "year of book release"
      - name: stock
        description: "stock of book available"
      - name: created_at
        description: "timestamp of creation"
      - name: model_creation_date
        description: "date of model creation"
      - name: model_updated_date
        description: "date of model update"
  - name: dim_members
    description: "dimensional table containing members data"
    columns:
      - name: id
        description: "unique member id"
      - name: name
        description: "name of member"
      - name: date_of_birth
        description: "birthdate of member"
      - name: age
        description: "age of member based on date_of_birth"
      - name: created_at
        description: "timestamp member data creation"
      - name: model_creation_date
        description: "date of model creation"
      - name: model_updated_date
        description: "date of model update"
  - name: fct_rent_transactions
    description: "Fact table containing rent transactions"
    columns:
      - name: id
        description: "unique id of rent_transaction"
      - name: book_id
        description: "unique rented book id"
      - name: member_id
        description: "unique id of renter"
      - name: rent_date
        description: "rent datetime"
      - name: return_date
        description: "expected book return date"
      - name: created_at
        description: "time of rent data creation"
      - name: no_rent_days
        description: "calculated number of rent days based on rent and return date"
      - name: model_creation_date
        description: "date of model creation"
      - name: model_updated_date
        description: "date of model update"
  - name: mart_rent_transactions
    description: "Data Mart containing detailed rent transactions data"
    columns:
      - name: id
        description: "unique id of rent_transaction"
      - name: book_id
        description: "unique rented book id"
      - name: book_name
        description: "column containing book title"
      - name: member_id
        description: "unique id of renter"
      - name: renter_name
        description: "name of member"
      - name: renter_age
        description: "age of member based on date_of_birth"
      - name: rent_day
        description: "rent day in day of the week"
      - name: return_day
        description: "return day in day of the week"
      - name: rent_date
        description: "rent datetime"
      - name: return_date
        description: "expected book return date"
      - name: no_rent_days
        description: "calculated number of rent days based on rent and return date"
      - name: created_at
        description: "time of rent data creation"
      - name: model_creation_date
        description: "date of model creation"
      - name: model_updated_date
        description: "date of model update"