version: 2

sources:
  - name: purwadika
    schema: ihsan_perpustakaan_final_project
    tables:
      - name: books_data
        identifier: books
      - name: member_data
        identifier: member
      - name: rent_data
        identifier: rent