library_dbt:
  outputs:
    capstoneThree:
      dataset: ihsan_perpustakaan_capstone_project_3
      job_execution_timeout_seconds: 200
      job_retries: 1
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: purwadika
      threads: 1
      keyfile: /opt/dbt/keys/bigquery-project.json
      type: bigquery
    source_destination:
      dataset: ihsan_dwh__perpustakaan_source
      job_execution_timeout_seconds: 200
      job_retries: 1
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: purwadika
      threads: 1
      keyfile: /opt/dbt/keys/bigquery-project.json
      type: bigquery
  target: source_destination