library_dbt:
  outputs:
    dev:
      dataset: ihsan_dwh_library_data_modelling
      job_execution_timeout_seconds: 200
      job_retries: 1
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: purwadika
      threads: 1
      type: bigquery
  target: dev