postgres:
  host: "application_postgres"
  port: 5432
  database: "application_db"
  username: "library_admin"
  password: "letsreadbook"

bigquery:
  project: "purwadika"
  dataset: "ihsan_perpustakaan_final_project_3"
  dataset_dwh_source: "dwh_ihsan_perpustakaan_source"
  dataset_dwh: "dwh_ihsan_perpusatakaan"
  dataset_dwh_mart: "dwh_ihsan_perpustakaan_mart"

temp_storage:
  type: "local"
  location: "/tmp/data"

tables:
  - source: "books_table"
    staging_table: "stg_books"
    destination: "books"
  - source: "library_member"
    staging_table: "stg_member"
    destination: "member"
  - source: "rent_table"
    staging_table: "stg_rent"
    destination: "rent"

source_tables:
  - source: "books"
    destination: "production_books_source"
  - source: "member"
    destination: "production_member_source"
  - source: "rent"
    destination: "production_rent_source"
