postgres:
  host: "application_postgres"
  port: 5432
  database: "application_db"
  username: "library_admin"
  password: "letsreadbook"

bigquery:
  project: "purwadika"
  dataset: "ihsan_perpustakaan_final_project"

temp_storage:
  type: "local"
  location: "/tmp/data"

tables:
  - source: "books_table"
    staging_table: "stg_books"
    destination: "books"
  - source: "library_member"
    staging_table: "stg_member"
    destination: "member"
  - source: "rent_table"
    staging_table: "stg_rent"
    destination: "rent"

models:
  source:
    tables:
      - name : "production_library_books_source"
      - name : "production_library_members_source"
      - name : "production_library_rent_transaction_source"
    target: "source_destination"
  dims:
    tables:
      - name : "dim_books"
      - name : "dim_genre"
      - name : "dim_members"
    target: "dwh_production"
  facts:
    tables:
      - name : "fct_rent_transactions"
    target: "dwh_production"
  mart:
    tables:
      - name: "mart_rent_transactions"
    target: "dwh_mart"
